config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :appointments
  resources :visitors
  resources :payments
  resources :zookeepers
  resources :animal_placements
  resources :animals
  resources :categories
    authenticate :user, lambda { |u| u.admin? } do
      mount Sidekiq::Web => '/sidekiq'
    end


  devise_for :users
  root to: 'animals#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/visitor.rb
class Visitor < ApplicationRecord
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
  before_action :set_visitor, only: %i[ show edit update destroy ]

  # GET /visitors or /visitors.json
  def index
    @visitors = Visitor.all
  end

  # GET /visitors/1 or /visitors/1.json
  def show
  end

  # GET /visitors/new
  def new
    @visitor = Visitor.new
  end

  # GET /visitors/1/edit
  def edit
  end

  # POST /visitors or /visitors.json
  def create
    @visitor = Visitor.new(visitor_params)

    respond_to do |format|
      if @visitor.save
        format.html { redirect_to visitor_url(@visitor), notice: "Visitor was successfully created." }
        format.json { render :show, status: :created, location: @visitor }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @visitor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /visitors/1 or /visitors/1.json
  def update
    respond_to do |format|
      if @visitor.update(visitor_params)
        format.html { redirect_to visitor_url(@visitor), notice: "Visitor was successfully updated." }
        format.json { render :show, status: :ok, location: @visitor }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @visitor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /visitors/1 or /visitors/1.json
  def destroy
    @visitor.destroy

    respond_to do |format|
      format.html { redirect_to visitors_url, notice: "Visitor was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_visitor
      @visitor = Visitor.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def visitor_params
      params.require(:visitor).permit(:name, :gender, :phonenumber, :email, :address)
    end
end

app/helpers/visitors_helper.rb
module VisitorsHelper
end

app/views/visitors/_form.html.erb
<%= form_with(model: visitor) do |form| %>
<% if visitor.errors.any? %>
<div id="error_explanation" class="bg-red-50 p-6 rounded text-red-800">
  <h2 class="text-lg font-semibold mb-3"><%= pluralize(visitor.errors.count, "error") %> prohibited this visitor from being saved:</h2>

  <ul class="list-disc leading-relaxed">
    <% visitor.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

  <div class="mb-6">
        <%= form.label :name, class: label_class %>
          <%= form.text_field :name, class: input_class %>
      </div>
  <div class="mb-6">
        <%= form.label :gender, class: label_class %>
          <%= form.text_field :gender, class: input_class %>
      </div>
  <div class="mb-6">
        <%= form.label :phonenumber, class: label_class %>
          <%= form.text_field :phonenumber, class: input_class %>
      </div>
  <div class="mb-6">
        <%= form.label :email, class: label_class %>
          <%= form.text_field :email, class: input_class %>
      </div>
  <div class="mb-6">
        <%= form.label :address, class: label_class %>
          <%= form.text_field :address, class: input_class %>
      </div>

<%= form.submit class: button_class(theme: 'primary') %>

<% if visitor.persisted? %>
<%= link_to "Cancel", visitor, class: "text-neutral-700 underline inline-block ml-3" %>
<% else %>
<%= link_to "Cancel", visitors_path, class:  "text-neutral-700 underline inline-block ml-3" %>
<% end %>
<% end %>

app/views/visitors/_visitor.html.erb
<div id="<%= dom_id visitor %>">
  <p>
    <strong>Name:</strong>
    <%= visitor.name %>
  </p>

  <p>
    <strong>Gender:</strong>
    <%= visitor.gender %>
  </p>

  <p>
    <strong>Phonenumber:</strong>
    <%= visitor.phonenumber %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= visitor.email %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= visitor.address %>
  </p>

</div>

app/views/visitors/edit.html.erb
<div class="max-w-3xl mx-auto px-4">
  <div class="flex items-center justify-between mb-6 flex-wrap">
    <h1 class="font-bold text-3xl mb-6">Edit visitor</h1>
    <% if @visitor.persisted? %>
    <%= button_to 'Destroy', @visitor, method: :delete, class: "text-red-700 underline", data: { turbo_confirm: 'Are you sure?' } %>
    <% end %>
  </div>

  <%= render 'form', visitor: @visitor %>
</div>

app/views/visitors/index.html.erb
<div class="container mx-auto px-4">
  <div class="flex items-center justify-between flex-wrap mb-6">
    <h1 class="text-3xl font-bold">Visitors</h1>

    <%= link_to new_visitor_path, class: button_class(theme: "primary") do %>
    Add New Visitor
    <% end %>
  </div>

  <table class="table-auto border-collapse border-slate-400 w-full">
    <thead class="bg-slate-50 dark:bg-slate-700">
      <tr>
        
          <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Name</th>
        
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Gender</th>
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Phonenumber</th>
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Email</th>
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Address</th>
                
      </tr>
    </thead>

    <tbody>
      <% @visitors.each do |visitor| %>
      <%= content_tag :tr, id: dom_id(visitor), class: dom_class(visitor) do %>
      
        <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= link_to visitor.name, visitor %></td>
      

              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= visitor.gender %></td>
              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= visitor.phonenumber %></td>
              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= visitor.email %></td>
              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= visitor.address %></td>
      
      
      <% end %>
      <% end %>
    </tbody>
  </table>
</div>
</div>

app/views/visitors/new.html.erb
<div class="max-w-3xl mx-auto px-4">
  <h1 class="font-bold text-3xl mb-6">New visitor</h1>

  <%= render 'form', visitor: @visitor %>
</div>

app/views/visitors/show.html.erb
<div class="max-w-3xl mx-auto px-4">
  <div class="flex items-center justify-between">
    <h1 class="flex-1 font-bold text-3xl">Visitor</h1>

    <div class="flex-wrap lg:flex items-center lg:space-x-3">
      <%= link_to visitors_path, class: button_class(theme: "transparent") do %>
      All Visitors
      <% end %>
      <%= link_to edit_visitor_path(@visitor), class: button_class(theme:"primary") do %>
      Edit
      <% end %>
    </div>
  </div>

  <ul class="text-slate-700">
      <li>
        <p class="font-semibold">Name:</p>
        <p><%= @visitor.name %></p>
      </li>
      <li>
        <p class="font-semibold">Gender:</p>
        <p><%= @visitor.gender %></p>
      </li>
      <li>
        <p class="font-semibold">Phonenumber:</p>
        <p><%= @visitor.phonenumber %></p>
      </li>
      <li>
        <p class="font-semibold">Email:</p>
        <p><%= @visitor.email %></p>
      </li>
      <li>
        <p class="font-semibold">Address:</p>
        <p><%= @visitor.address %></p>
      </li>
  </ul>
</div>