config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :appointments
  resources :visitors
  resources :payments
  resources :zookeepers
  resources :animal_placements
  resources :animals
  resources :categories
    authenticate :user, lambda { |u| u.admin? } do
      mount Sidekiq::Web => '/sidekiq'
    end


  devise_for :users
  root to: 'animals#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/zookeeper.rb
class Zookeeper < ApplicationRecord
end

app/controllers/zookeepers_controller.rb
class ZookeepersController < ApplicationController
  before_action :set_zookeeper, only: %i[ show edit update destroy ]

  # GET /zookeepers or /zookeepers.json
  def index
    @zookeepers = Zookeeper.all
  end

  # GET /zookeepers/1 or /zookeepers/1.json
  def show
  end

  # GET /zookeepers/new
  def new
    @zookeeper = Zookeeper.new
  end

  # GET /zookeepers/1/edit
  def edit
  end

  # POST /zookeepers or /zookeepers.json
  def create
    @zookeeper = Zookeeper.new(zookeeper_params)

    respond_to do |format|
      if @zookeeper.save
        format.html { redirect_to zookeeper_url(@zookeeper), notice: "Zookeeper was successfully created." }
        format.json { render :show, status: :created, location: @zookeeper }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @zookeeper.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /zookeepers/1 or /zookeepers/1.json
  def update
    respond_to do |format|
      if @zookeeper.update(zookeeper_params)
        format.html { redirect_to zookeeper_url(@zookeeper), notice: "Zookeeper was successfully updated." }
        format.json { render :show, status: :ok, location: @zookeeper }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @zookeeper.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /zookeepers/1 or /zookeepers/1.json
  def destroy
    @zookeeper.destroy

    respond_to do |format|
      format.html { redirect_to zookeepers_url, notice: "Zookeeper was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_zookeeper
      @zookeeper = Zookeeper.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def zookeeper_params
      params.require(:zookeeper).permit(:name, :dateofbirth)
    end
end

app/helpers/zookeepers_helper.rb
module ZookeepersHelper
end

app/views/zookeepers/_form.html.erb
<%= form_with(model: zookeeper) do |form| %>
<% if zookeeper.errors.any? %>
<div id="error_explanation" class="bg-red-50 p-6 rounded text-red-800">
  <h2 class="text-lg font-semibold mb-3"><%= pluralize(zookeeper.errors.count, "error") %> prohibited this zookeeper from being saved:</h2>

  <ul class="list-disc leading-relaxed">
    <% zookeeper.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

  <div class="mb-6">
        <%= form.label :name, class: label_class %>
          <%= form.text_field :name, class: input_class %>
      </div>
  <div class="mb-6">
        <%= form.label :dateofbirth, class: label_class %>
          <%= form.text_field :dateofbirth, class: input_class %>
      </div>

<%= form.submit class: button_class(theme: 'primary') %>

<% if zookeeper.persisted? %>
<%= link_to "Cancel", zookeeper, class: "text-neutral-700 underline inline-block ml-3" %>
<% else %>
<%= link_to "Cancel", zookeepers_path, class:  "text-neutral-700 underline inline-block ml-3" %>
<% end %>
<% end %>

app/views/zookeepers/_zookeeper.html.erb
<div id="<%= dom_id zookeeper %>">
  <p>
    <strong>Name:</strong>
    <%= zookeeper.name %>
  </p>

  <p>
    <strong>Dateofbirth:</strong>
    <%= zookeeper.dateofbirth %>
  </p>

</div>

app/views/zookeepers/edit.html.erb
<div class="max-w-3xl mx-auto px-4">
  <div class="flex items-center justify-between mb-6 flex-wrap">
    <h1 class="font-bold text-3xl mb-6">Edit zookeeper</h1>
    <% if @zookeeper.persisted? %>
    <%= button_to 'Destroy', @zookeeper, method: :delete, class: "text-red-700 underline", data: { turbo_confirm: 'Are you sure?' } %>
    <% end %>
  </div>

  <%= render 'form', zookeeper: @zookeeper %>
</div>

app/views/zookeepers/index.html.erb
<div class="container mx-auto px-4">
  <div class="flex items-center justify-between flex-wrap mb-6">
    <h1 class="text-3xl font-bold">Zookeepers</h1>

    <%= link_to new_zookeeper_path, class: button_class(theme: "primary") do %>
    Add New Zookeeper
    <% end %>
  </div>

  <table class="table-auto border-collapse border-slate-400 w-full">
    <thead class="bg-slate-50 dark:bg-slate-700">
      <tr>
        
          <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Name</th>
        
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Dateofbirth</th>
                
      </tr>
    </thead>

    <tbody>
      <% @zookeepers.each do |zookeeper| %>
      <%= content_tag :tr, id: dom_id(zookeeper), class: dom_class(zookeeper) do %>
      
        <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= link_to zookeeper.name, zookeeper %></td>
      

              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= zookeeper.dateofbirth %></td>
      
      
      <% end %>
      <% end %>
    </tbody>
  </table>
</div>
</div>

app/views/zookeepers/new.html.erb
<div class="max-w-3xl mx-auto px-4">
  <h1 class="font-bold text-3xl mb-6">New zookeeper</h1>

  <%= render 'form', zookeeper: @zookeeper %>
</div>

app/views/zookeepers/show.html.erb
<div class="max-w-3xl mx-auto px-4">
  <div class="flex items-center justify-between">
    <h1 class="flex-1 font-bold text-3xl">Zookeeper</h1>

    <div class="flex-wrap lg:flex items-center lg:space-x-3">
      <%= link_to zookeepers_path, class: button_class(theme: "transparent") do %>
      All Zookeepers
      <% end %>
      <%= link_to edit_zookeeper_path(@zookeeper), class: button_class(theme:"primary") do %>
      Edit
      <% end %>
    </div>
  </div>

  <ul class="text-slate-700">
      <li>
        <p class="font-semibold">Name:</p>
        <p><%= @zookeeper.name %></p>
      </li>
      <li>
        <p class="font-semibold">Dateofbirth:</p>
        <p><%= @zookeeper.dateofbirth %></p>
      </li>
  </ul>
</div>