config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :appointments
  resources :visitors
  resources :payments
  resources :zookeepers
  resources :animal_placements
  resources :animals
  resources :categories
    authenticate :user, lambda { |u| u.admin? } do
      mount Sidekiq::Web => '/sidekiq'
    end


  devise_for :users
  root to: 'animals#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/animal.rb
class Animal < ApplicationRecord
	belongs_to :category

	validates_presence_of :name, :dateofbirth, :characteristic
	validates_uniqueness_of :name 

end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
  before_action :set_animal, only: %i[ show edit update destroy ]

  # GET /animals or /animals.json
  def index
    @animals = Animal.all
  end

  # GET /animals/1 or /animals/1.json
  def show
  end

  # GET /animals/new
  def new
    @animal = Animal.new
  end

  # GET /animals/1/edit
  def edit
  end

  # POST /animals or /animals.json
  def create
    @animal = Animal.new(animal_params)

    respond_to do |format|
      if @animal.save
        format.html { redirect_to animal_url(@animal), notice: "Animal was successfully created." }
        format.json { render :show, status: :created, location: @animal }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @animal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /animals/1 or /animals/1.json
  def update
    respond_to do |format|
      if @animal.update(animal_params)
        format.html { redirect_to animal_url(@animal), notice: "Animal was successfully updated." }
        format.json { render :show, status: :ok, location: @animal }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @animal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /animals/1 or /animals/1.json
  def destroy
    @animal.destroy

    respond_to do |format|
      format.html { redirect_to animals_url, notice: "Animal was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_animal
      @animal = Animal.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def animal_params
      params.require(:animal).permit(:name, :dateofbirth, :age, :characteristic, :food, :category_id)
    end
end

app/helpers/animals_helper.rb
module AnimalsHelper
end

app/views/animals/_animal.html.erb
<div id="<%= dom_id animal %>">
  <p>
    <strong>Name:</strong>
    <%= animal.name %>
  </p>

  <p>
    <strong>Dateofbirth:</strong>
    <%= animal.dateofbirth %>
  </p>

  <p>
    <strong>Age:</strong>
    <%= animal.age %>
  </p>

  <p>
    <strong>Characteristic:</strong>
    <%= animal.characteristic %>
  </p>

  <p>
    <strong>Food:</strong>
    <%= animal.food %>
  </p>

  <p>
    <strong>Category:</strong>
    <%= animal.category_id %>
  </p>

</div>

app/views/animals/_form.html.erb
<%= form_with(model: animal) do |form| %>
<% if animal.errors.any? %>
<div id="error_explanation" class="bg-red-50 p-6 rounded text-red-800">
  <h2 class="text-lg font-semibold mb-3"><%= pluralize(animal.errors.count, "error") %> prohibited this animal from being saved:</h2>

  <ul class="list-disc leading-relaxed">
    <% animal.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

  <div class="mb-6">
        <%= form.label :name, class: label_class %>
          <%= form.text_field :name, class: input_class %>
      </div>
  <div class="mb-6">
        <%= form.label :dateofbirth, class: label_class %>
          <%= form.date_field :dateofbirth, class: input_class %>
      </div>
  <div class="mb-6">
        <%= form.label :age, class: label_class %>
          <%= form.number_field :age, class: input_class %>
      </div>
  <div class="mb-6">
        <%= form.label :characteristic, class: label_class %>
          <%= form.text_field :characteristic, class: input_class %>
      </div>
  <div class="mb-6">
        <%= form.label :food, class: label_class %>
          <%= form.text_field :food, class: input_class %>
      </div>
  <div class="mb-6">
        <%= form.label :category_id, class: label_class %>
          <%= form.select :category_id, options_from_collection_for_select(
Category.all, 'id', 'specy', selected = animal.category_id), class: label_class %>
      </div>

<%= form.submit class: button_class(theme: 'primary') %>

<% if animal.persisted? %>
<%= link_to "Cancel", animal, class: "text-neutral-700 underline inline-block ml-3" %>
<% else %>
<%= link_to "Cancel", animals_path, class:  "text-neutral-700 underline inline-block ml-3" %>
<% end %>
<% end %>

app/views/animals/edit.html.erb
<div class="max-w-3xl mx-auto px-4">
  <div class="flex items-center justify-between mb-6 flex-wrap">
    <h1 class="font-bold text-3xl mb-6">Edit animal</h1>
    <% if @animal.persisted? %>
    <%= button_to 'Destroy', @animal, method: :delete, class: "text-red-700 underline", data: { turbo_confirm: 'Are you sure?' } %>
    <% end %>
  </div>

  <%= render 'form', animal: @animal %>
</div>

app/views/animals/index.html.erb
<div class="container mx-auto px-4">
  <div class="flex items-center justify-between flex-wrap mb-6">
    <h1 class="text-3xl font-bold">Animals</h1>

    <%= link_to new_animal_path, class: button_class(theme: "primary") do %>
    Add New Animal
    <% end %>
  </div>

  <table class="table-auto border-collapse border-slate-400 w-full">
    <thead class="bg-slate-50 dark:bg-slate-700">
      <tr>
        
          <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Name</th>
        
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Dateofbirth</th>
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Age</th>
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Characteristic</th>
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Food</th>
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Category</th>
                
      </tr>
    </thead>

    <tbody>
      <% @animals.each do |animal| %>
      <%= content_tag :tr, id: dom_id(animal), class: dom_class(animal) do %>
      
        <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= link_to animal.name, animal %></td>
      

              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= animal.dateofbirth %></td>
              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= animal.age %></td>
              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= animal.characteristic %></td>
              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= animal.food %></td>
              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= animal.category.specy %></td>
      
      
      <% end %>
      <% end %>
    </tbody>
  </table>
</div>
</div>

app/views/animals/new.html.erb
<div class="max-w-3xl mx-auto px-4">
  <h1 class="font-bold text-3xl mb-6">New animal</h1>

  <%= render 'form', animal: @animal %>
</div>

app/views/animals/show.html.erb
<div class="max-w-3xl mx-auto px-4">
  <div class="flex items-center justify-between">
    <h1 class="flex-1 font-bold text-3xl">Animal</h1>

    <div class="flex-wrap lg:flex items-center lg:space-x-3">
      <%= link_to animals_path, class: button_class(theme: "transparent") do %>
      All Animals
      <% end %>
      <%= link_to edit_animal_path(@animal), class: button_class(theme:"primary") do %>
      Edit
      <% end %>
    </div>
  </div>

  <ul class="text-slate-700">
      <li>
        <p class="font-semibold">Name:</p>
        <p><%= @animal.name %></p>
      </li>
      <li>
        <p class="font-semibold">Dateofbirth:</p>
        <p><%= @animal.dateofbirth %></p>
      </li>
      <li>
        <p class="font-semibold">Age:</p>
        <p><%= @animal.age %></p>
      </li>
      <li>
        <p class="font-semibold">Characteristic:</p>
        <p><%= @animal.characteristic %></p>
      </li>
      <li>
        <p class="font-semibold">Food:</p>
        <p><%= @animal.food %></p>
      </li>
      <li>
        <p class="font-semibold">Category:</p>
        <p><%= @animal.category.specy %></p>
      </li>
  </ul>
</div>